name: PR lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  client_eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Change into client dir
        run: cd client
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint src
  client_prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Change into client dir
        run : cd client
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx prettier src --check

